study: # Configuration for training
  study_name: "purchase100-mlp3-baseline"
  trials: 50
  epochs: 50 # Integer number for indicating the epochs for training target model.
  batch_size: 128 # Integer number for indicating batch size for training the target model.
  optimizer: SGD # String which indicates the optimizer.
  model: mlp3
  root: ./study

data: # Configuration for data
  dataset: purchase100 # String indicates the name of the dataset
  f_train: 0.5 # Float number from 0 to 1 indicating the fraction of the train dataset
  f_test: 0.5 # Float number from 0 to 1 indicating the size of the test set
  root: ./data # String about where to save the data.


