train: # Configuration for training
  study_name: texas100-mlp3-baseline-db7c7aba7a # Baseline study to load params from
  epochs: 50 # Integer number for indicating the epochs for training target model. For speedyresnet, it uses its own number of epochs.

data: # Configuration for data
  dataset: texas100 # String indicates the name of the dataset
  f_train: 0.5 # Float number from 0 to 1 indicating the fraction of the train dataset
  f_test: 0.5 # Float number from 0 to 1 indicating the size of the test set
  root: ./data # String about where to save the data.
